service: my-app
frameworkVersion: '2 || 3'

package:
  exclude:
    - './**'
  include:
    - './handler.py'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-python-requirements
  - serverless-localstack

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    autostart: true  # optional - Start LocalStack in Docker on Serverless deploy
    networks: #optional - attaches the list of networks to the localstack docker container after startup
      - host
      - overlay
      - localstack-net
    lambda:
      # Enable this flag to improve performance
      mountCode: false  # specify either "true", or a relative path to the root Lambda mount path
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: False
  pythonRequirements:
    fileName: requirements.txt
    dockerizePip: false

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
